name: Auto Update Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Version JSON
        run: |
          echo "{\"version\": \"${{ vars.VERSION_BASE }}.${{ github.run_number }}\", \"buildDate\": \"$(date +'%Y-%m-%d %H:%M')\"}" > version.json

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.json
          git diff-index --quiet HEAD || git commit -m "chore: auto-update version [skip ci]"
          git push
